env:
  global:
    secure: "TlOj3I6uQJQd86NmxeeMGyqwSLwVtypMAldJ0+22/Wi9vYiF/rmguNgRBMUY4t1JS5vekNsOIzt802eBd6jWaesplKvtgTySQ/29MPNJYlLA6PkSIA2Cvd/TXM6BJ57PMxXE3c2LXjP6+DqdMPf/Qk/WdipL5lPFgH76bCe6eq0uzNvlGEYv61loBUr4y4TowU2t0NkYuOiULvwhJC2AzK/tq7mhy0/k8f8ehJ3QTdyjitbU8TF6nJwxG0MAfwLuBkrdrk7b85O3HQaPgXOkoPMXlLLCuB3sOwrF2BGGa+sUOyYLGQrWM2ffkAwDrpDsV21crmnjaIzgTe5T8M/eTQ8NW/kaWaxvqKPbmCMIqxbhPWBstbiTn7xCem+NXzq4Krvt5jifI30zpa4U4dGz6d/zHjx9HRExXOPE2xFqL3H6k25+O0D4MeRHnEU6nHfHFQxdd1zHmr4Y/lKPwQh9kL6xtkVk622f1P+i258NMcy361+BJiLQhk9Q2FZziUjJPfl+pzwOdo60fkiU62SB9iS4/DwIJgJTjqP3upp3xcApwSFKufjEBn9TKiz3c87+8UefrV87UfbvuyMqrXOJNs6+U25WmVuGMebezvlNnwrBK+8glXqia91g9mvNLe7/KwQHAcAR8Km7Dwc7JEfLJXnqWZsyEv+zz38FuIEq2RM="

language: common-lisp

env:
  matrix:
    - LISP=sbcl

install:
  - sudo apt-get install info install-info
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^#cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  - git clone --depth=1 git://github.com/shamazmazum/codex.git ~/lisp/codex
  - cl -l codex -l flexi-streams -l fiveam -e '(ql-util:without-prompting (ql:add-to-init-file))'

script:
  - cl -f $TRAVIS_BUILD_DIR/tests/travis.lisp
  - cl -l codex -e '(codex:document :easy-audio :skip-undocumented t)'

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: "$GITHUB_TOKEN"
#  keep_history: true
#  local_dir: "$TRAVIS_BUILD_DIR/docs/build/easy-audio/html"
#  edge: true
#  on:
#    branch: master
